<template>
  <v-dialog
    :model-value="modelValue"
    max-width="72rem"
    scrollable
    @update:model-value="attemptClose"
  >
    <v-card class="wizard">
      <div class="wizard__steps">
        <div
          v-for="(label, index) in STEP_LABELS"
          :key="label"
          class="wizard__step"
        >
          <span
            class="wizard__dot"
            :class="{ 'wizard__dot--active': step === index + 1 }"
          />
          <span class="wizard__step-label">{{ label }}</span>
          <span
            v-if="index < STEP_LABELS.length - 1"
            class="wizard__line"
          />
        </div>
      </div>

      <h2 class="wizard__title">
        {{ stepTitle }}
      </h2>

      <v-card-text class="wizard__body">
        <section
          v-if="step === 1"
          class="wizard__grid"
        >
          <div class="wizard__field">
            <label
              class="wizard__label"
              for="event-type"
            ><span class="wizard__required">*</span>Event Type to create</label>
            <v-select
              id="event-type"
              v-model="eventTypeKey"
              :items="eventTypeItems"
              item-title="name"
              item-value="key"
              placeholder="Pick an event type"
            />
          </div>

          <div class="wizard__field">
            <label
              class="wizard__label"
              for="industry"
            ><span class="wizard__required">*</span>Industry</label>
            <v-select
              id="industry"
              v-model="industry"
              :items="industries"
              item-title="name"
              item-value="key"
              placeholder="Pick an industry"
            />
          </div>

          <div class="wizard__field">
            <label
              class="wizard__label"
              for="platform"
            >
              <span class="wizard__required">*</span>Platform
              <SkyInfoIcon label="What Platform accepts">
                Pick one of the platforms already used in the system, or type a new name to create it.
                The list is built from the platforms of the events that exist.
              </SkyInfoIcon>
            </label>
            <v-combobox
              id="platform"
              v-model="platform"
              :items="platformOptions"
              placeholder="Enter platform"
            />
          </div>

          <div class="wizard__field">
            <label
              class="wizard__label"
              for="status"
            ><span class="wizard__required">*</span>Status</label>
            <v-select
              id="status"
              v-model="status"
              :items="STATUS_OPTIONS"
              placeholder="Pick a status"
            />
          </div>

          <div class="wizard__field">
            <label
              class="wizard__label"
              for="event-name"
            >
              <span class="wizard__required">*</span>Event Name
              <SkyInfoIcon label="What Event Name means">
                The name this event is listed and searched by, so give it something you will recognise later.
                It is required: an event without a name is one nobody can tell apart from the next one.
              </SkyInfoIcon>
            </label>
            <v-text-field
              id="event-name"
              v-model="name"
              placeholder="Enter event name"
            />
          </div>

          <div class="wizard__field">
            <label
              class="wizard__label"
              for="reference-id"
            >
              Reference ID
              <SkyInfoIcon label="What Reference ID means">
                The identifier you already know this event by, carried over from wherever it was reported.
                It is yours to choose, it has to be unique, and it is the one you can search by. The EVENT ID
                beside it is generated by the system when the event is stored and can never be set or changed.
              </SkyInfoIcon>
            </label>
            <v-text-field
              id="reference-id"
              v-model="referenceId"
              placeholder="Enter reference id"
            />
          </div>

          <!--
            The moment the activity happened and the moment it was uploaded are two different things, so the
            date is asked for here while created at keeps recording the upload on its own.
          -->
          <div class="wizard__field">
            <label
              class="wizard__label"
              for="event-date"
            >Event Date</label>
            <v-text-field
              id="event-date"
              v-model="eventDate"
              type="date"
            />
          </div>

          <div class="wizard__field">
            <label
              class="wizard__label"
              for="experiment-result"
            >Experiment Result</label>
            <v-select
              id="experiment-result"
              v-model="experimentResult"
              :items="RESULT_OPTIONS"
              placeholder="Not known yet"
              clearable
            />
          </div>

          <div class="wizard__field wizard__field--wide">
            <label
              class="wizard__label"
              for="information"
            >
              Information
              <SkyInfoIcon label="What Information means">
                Anything worth knowing about this event, written as freely as you like. The line breaks you
                type are kept, so the text is read back laid out the way you wrote it.
              </SkyInfoIcon>
            </label>
            <v-textarea
              id="information"
              v-model="notes"
              rows="4"
              placeholder="Type here..."
            />
          </div>

          <div class="wizard__field wizard__field--wide">
            <FileDropzone
              label="Additional Files"
              :files="eventFiles"
              @update:files="eventFiles = $event"
            />
          </div>
        </section>

        <section v-else-if="step === 2">
          <MetadataFieldsPanel
            v-model="industryValues"
            :fields="industryFields"
            title="Industry fields"
          />
        </section>

        <section
          v-else
          class="wizard__additional"
        >
          <div class="wizard__entity-form">
            <EntityFormFields
              v-model="entityForm"
              :entity-types="entityTypes"
              :fields="entityFields"
              :origins="originOptions"
              :context="industryValues"
              id-prefix="wizard-entity"
            />

            <div class="wizard__entity-actions">
              <v-btn
                v-if="editedIndex !== null"
                variant="text"
                @click="cancelEntityEdit"
              >
                CANCEL
              </v-btn>
              <v-btn
                color="primary"
                :prepend-icon="editedIndex === null ? 'mdi-plus' : 'mdi-check'"
                :disabled="!canAddEntity"
                @click="commitEntity"
              >
                {{ editedIndex === null ? 'ADD' : 'UPDATE' }}
              </v-btn>
            </div>
          </div>

          <aside class="wizard__added">
            <h3 class="wizard__added-title">
              Added Entities - {{ addedEntities.length }}
            </h3>
            <!--
              An entity that was added is not finished with: something was mistyped, or a file was forgotten.
              Each row therefore opens back into the form instead of only offering to be thrown away.
            -->
            <div
              v-for="(entity, index) in addedEntities"
              :key="`${entity.form.name}-${index}`"
              class="wizard__added-item"
              :class="{ 'wizard__added-item--edited': editedIndex === index }"
            >
              <button
                type="button"
                class="wizard__added-open"
                :aria-label="`Edit ${entity.form.name}`"
                @click="editEntity(index)"
              >
                <strong>{{ entity.form.name }}</strong>
                <span class="wizard__added-hint">
                  {{ entity.typeName }} · {{ fileCount(entity) }} file(s)
                </span>
              </button>
              <v-btn
                icon="mdi-close"
                size="x-small"
                variant="text"
                :aria-label="`Remove ${entity.form.name}`"
                @click="removeEntity(index)"
              />
            </div>
            <p
              v-if="addedEntities.length === 0"
              class="wizard__empty"
            >
              Nothing was added yet.
            </p>
            <p
              v-else
              class="wizard__empty"
            >
              Pick one to load it back into the form and change it.
            </p>
          </aside>
        </section>
      </v-card-text>

      <v-card-actions class="wizard__actions">
        <v-btn
          v-if="step > 1"
          variant="outlined"
          @click="step -= 1"
        >
          BACK
        </v-btn>
        <v-spacer />
        <v-btn
          v-if="step < 3"
          variant="outlined"
          :disabled="!canContinue"
          @click="goNext"
        >
          NEXT
        </v-btn>
        <v-btn
          v-else
          color="primary"
          :loading="saving"
          :disabled="!canContinue"
          @click="submit"
        >
          CREATE
        </v-btn>
      </v-card-actions>
    </v-card>

    <UnsavedChangesDialog
      v-model="confirmOpen"
      @discard="discard"
    />
  </v-dialog>
</template>

<script lang="ts">
import type { EventStatus, ExperimentResult, JsonValue } from '@/models/common'
import { SkyDropzone as FileDropzone, SkyInfoIcon, toIsoDate } from '@skyscanner/sky-ui'
import type { EntityCreateRequest, EntityType } from '@/models/entity'
import type { EventDetail, EventType } from '@/models/event'
import type { FieldDefinition } from '@/models/field'

interface Props {
  modelValue: boolean
  defaultIndustry?: string | null
}

interface Emits {
  (event: 'update:modelValue', value: boolean): void
  (event: 'created', created: EventDetail): void
}

/** One entity the wizard collected, kept in the very shape the shared form works with. */
interface EntityDraft {
  typeName: string
  form: EntityFormValue
}
</script>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'

import EntityFormFields, { emptyEntityForm, type EntityFormValue } from '@/components/EntityFormFields.vue'
import MetadataFieldsPanel from '@/components/MetadataFieldsPanel.vue'
import UnsavedChangesDialog from '@/components/UnsavedChangesDialog.vue'
import { useDirtyGuard } from '@/composables/useDirtyGuard'
import { useSnackbar } from '@/composables/useSnackbar'
import { useIndustries } from '@/composables/useIndustries'
import { createEvent } from '@/requests/events'
import { readColumnValues } from '@/requests/grid'
import { listEntityTypes, listEventTypes, listFields } from '@/requests/schema'
import { uploadArtifacts } from '@/requests/storage'
import { applicableFields } from '@/utils/dependencies'
import { toMetadataAttributes } from '@/utils/rows'

const STEP_LABELS: string[] = ['Data', 'Industry Fields', 'Add Entities']
const STEP_TITLES: string[] = [
  'Create An Event',
  'Fill Industry Specific Fields',
  'Add Entities To The Event',
]
const STATUS_OPTIONS: EventStatus[] = ['draft', 'raw', 'parsed', 'partial', 'failed', 'archived']
const RESULT_OPTIONS: ExperimentResult[] = ['successful', 'partial', 'failed']

const props = withDefaults(defineProps<Props>(), { defaultIndustry: null })
const emit = defineEmits<Emits>()

const { industries, load: loadIndustries } = useIndustries()
const { notify, reportError } = useSnackbar()

const step = ref<number>(1)
const saving = ref<boolean>(false)

const eventTypes = ref<EventType[]>([])
const entityTypes = ref<EntityType[]>([])
const industryFields = ref<FieldDefinition[]>([])
const entityFields = ref<FieldDefinition[]>([])
const platformOptions = ref<string[]>([])

const eventTypeKey = ref<string | null>(null)
const industry = ref<string | null>(props.defaultIndustry)
const platform = ref<string>('')
const status = ref<EventStatus>('raw')
const name = ref<string>('')
const referenceId = ref<string>('')
const eventDate = ref<string>('')
const experimentResult = ref<ExperimentResult | null>(null)
const notes = ref<string>('')
const eventFiles = ref<File[]>([])
const industryValues = ref<Record<string, JsonValue>>({})

const entityForm = ref<EntityFormValue>(emptyEntityForm())
const addedEntities = ref<EntityDraft[]>([])

/* Which of the added entities the form is currently holding, or null while the form is collecting a new one. */
const editedIndex = ref<number | null>(null)

/* What the wizard looked like when it opened, which is what tells a touched form from an untouched one. */
const openedWith = ref<string>('')

const eventTypeItems = computed<EventType[]>(() => eventTypes.value)

const stepTitle = computed<string>(() => STEP_TITLES[step.value - 1] ?? STEP_TITLES[0])

const visibleIndustryFields = computed<FieldDefinition[]>(() =>
  applicableFields(industryFields.value, industryValues.value),
)

/**
 * Describe the whole wizard as one comparable string.
 *
 * Files carry no value equality of their own, so they are described by what identifies them to the user -
 * the name and the size - rather than by the object the picker handed over.
 */
const describeFiles = (files: File[]): string[] => files.map((file) => `${file.name}:${file.size}`)

/** Describe one entity form, with its files reduced to what identifies them. */
const describeForm = (form: EntityFormValue): JsonValue => ({
  ...form,
  rawFiles: describeFiles(form.rawFiles),
  parsedFiles: describeFiles(form.parsedFiles),
  parsedAdditionalFiles: describeFiles(form.parsedAdditionalFiles),
})

const snapshot = (): string =>
  JSON.stringify({
    eventTypeKey: eventTypeKey.value,
    industry: industry.value,
    platform: platform.value,
    status: status.value,
    name: name.value,
    referenceId: referenceId.value,
    eventDate: eventDate.value,
    experimentResult: experimentResult.value,
    notes: notes.value,
    files: describeFiles(eventFiles.value),
    industryValues: industryValues.value,
    entityForm: describeForm(entityForm.value),
    addedEntities: addedEntities.value.map((draft) => describeForm(draft.form)),
  })

const originOptions = computed<string[]>(() =>
  industry.value === null ? [] : (industries.value.find((item) => item.key === industry.value)?.entity_origins ?? []),
)

/* The same rule the service enforces: an entity needs a type and a name before it can be added. */
const canAddEntity = computed<boolean>(
  () => entityForm.value.typeKey !== null && entityForm.value.name.trim().length > 0,
)

const fileCount = (entity: EntityDraft): number =>
  entity.form.rawFiles.length + entity.form.parsedFiles.length + entity.form.parsedAdditionalFiles.length

const canContinue = computed<boolean>(() => {
  if (step.value === 1) {
    /* The name is what the event is listed and searched by, so an event without one cannot be started. */
    return (
      eventTypeKey.value !== null &&
      industry.value !== null &&
      platform.value.length > 0 &&
      name.value.trim().length > 0
    )
  }

  if (step.value === 2) {
    return visibleIndustryFields.value
      .filter((field) => field.required)
      .every((field) => {
        const value = industryValues.value[field.key]

        return value !== null && value !== undefined && String(value).length > 0
      })
  }

  return true
})

const loadSchema = async (): Promise<void> => {
  try {
    const selected = industry.value
    const [types, entities, fields, platforms] = await Promise.all([
      listEventTypes(selected),
      listEntityTypes(selected),
      listFields({ scope: 'event', industry: selected }),
      readColumnValues('platform'),
    ])
    eventTypes.value = types
    entityTypes.value = entities
    industryFields.value = fields
    platformOptions.value = platforms
  } catch (error) {
    reportError(error)
  }
}

const loadEntityFields = async (): Promise<void> => {
  const typeKey = entityForm.value.typeKey
  if (typeKey === null) {
    entityFields.value = []
    return
  }

  try {
    entityFields.value = await listFields({
      scope: 'entity',
      industry: industry.value,
      entityType: typeKey,
    })
  } catch (error) {
    reportError(error)
  }
}

const reset = () => {
  step.value = 1
  eventTypeKey.value = null
  industry.value = props.defaultIndustry
  platform.value = ''
  status.value = 'raw'
  name.value = ''
  referenceId.value = ''
  eventDate.value = ''
  experimentResult.value = null
  notes.value = ''
  eventFiles.value = []
  industryValues.value = {}
  entityForm.value = emptyEntityForm()
  addedEntities.value = []
  editedIndex.value = null
  openedWith.value = snapshot()
}

const close = () => {
  emit('update:modelValue', false)
}

const { confirmOpen, attemptClose, discard } = useDirtyGuard({
  isDirty: () => snapshot() !== openedWith.value,
  close,
})

const goNext = () => {
  step.value += 1
}

/** Empty the form for the next entity, keeping the type because three telemetries in a row is the common case. */
const clearEntityForm = () => {
  entityForm.value = { ...emptyEntityForm(), typeKey: entityForm.value.typeKey }
  editedIndex.value = null
}

/**
 * Put what the form holds into the list, either as a new entity or over the one being edited.
 */
const commitEntity = () => {
  const typeKey = entityForm.value.typeKey
  if (typeKey === null || !canAddEntity.value) {
    return
  }

  const declared = entityTypes.value.find((candidate) => candidate.key === typeKey)
  const draft: EntityDraft = {
    typeName: declared?.name ?? typeKey,
    form: { ...entityForm.value, name: entityForm.value.name.trim() },
  }
  const edited = editedIndex.value
  addedEntities.value =
    edited === null
      ? [...addedEntities.value, draft]
      : addedEntities.value.map((current, index) => (index === edited ? draft : current))

  clearEntityForm()
}

/**
 * Load an entity that was already added back into the form, so that it can be corrected rather than
 * removed and typed again from the start.
 */
const editEntity = (index: number) => {
  const draft = addedEntities.value[index]
  if (draft === undefined) {
    return
  }

  entityForm.value = { ...draft.form }
  editedIndex.value = index
}

const cancelEntityEdit = () => {
  clearEntityForm()
}

const removeEntity = (index: number) => {
  addedEntities.value = addedEntities.value.filter((_, candidate) => candidate !== index)

  /*
   * The form is holding one of these entities, and the list it points into just changed underneath it. The
   * entity it was editing is gone, so the form goes back to collecting a new one; anything after the removed
   * row has moved one place towards the front.
   */
  const edited = editedIndex.value
  if (edited === null) {
    return
  }

  if (edited === index) {
    clearEntityForm()

    return
  }

  editedIndex.value = edited > index ? edited - 1 : edited
}

const buildEntityRequests = async (): Promise<EntityCreateRequest[]> => {
  const requests: EntityCreateRequest[] = []
  for (const draft of addedEntities.value) {
    const owner = { ownerKind: 'entities' as const, ownerId: null }
    const [raw, parsed, additional] = await Promise.all([
      uploadArtifacts(draft.form.rawFiles, {
        ...owner,
        kind: 'raw',
        folder: 'raw_files',
        descriptor: `Raw files of ${draft.form.name}`,
      }),
      uploadArtifacts(draft.form.parsedFiles, {
        ...owner,
        kind: 'parsed',
        folder: 'parsed_files',
        descriptor: `Parsed files of ${draft.form.name}`,
      }),
      uploadArtifacts(draft.form.parsedAdditionalFiles, {
        ...owner,
        kind: 'parsed_additional',
        folder: 'parsed_additional_files',
        descriptor: `Extra parsing products of ${draft.form.name}`,
      }),
    ])
    requests.push({
      name: draft.form.name,
      entity_type_key: draft.form.typeKey ?? '',
      origin: draft.form.origin,
      code_version: draft.form.codeVersion.length > 0 ? draft.form.codeVersion : null,
      status: draft.form.status,
      notes: draft.form.notes,
      upload_source: 'manual',
      requested_at: null,
      received_at: null,
      raw_files: raw,
      parsed_files: parsed,
      parsed_additional_files: additional,
      metadata: toMetadataAttributes(draft.form.values),
    })
  }

  return requests
}

const submit = async (): Promise<void> => {
  if (eventTypeKey.value === null || industry.value === null) {
    return
  }

  /*
   * An entity that was loaded back into the form is already part of the list, so creating the event while it
   * is open would store the version from before the correction. Its changes are taken along instead.
   */
  if (editedIndex.value !== null && canAddEntity.value) {
    commitEntity()
  }

  saving.value = true
  try {
    const additionalFiles = await uploadArtifacts(eventFiles.value, {
      ownerKind: 'events',
      ownerId: null,
      kind: 'additional',
      folder: null,
      descriptor: 'Files attached while the event was created',
    })
    const entities = await buildEntityRequests()
    const created = await createEvent({
      name: name.value.trim(),
      reference_id: referenceId.value.trim(),
      event_type_keys: [eventTypeKey.value],
      industry: industry.value,
      platform: platform.value,
      status: status.value,
      experiment_result: experimentResult.value,
      event_date: toIsoDate(eventDate.value),
      notes: notes.value,
      upload_source: 'manual',
      additional_files: additionalFiles,
      metadata: toMetadataAttributes(industryValues.value),
      entities,
    })
    notify(`Event ${created.name} was created`, 'success')
    emit('created', created)
    close()
    reset()
  } catch (error) {
    reportError(error)
  } finally {
    saving.value = false
  }
}

watch(
  () => props.modelValue,
  async (open) => {
    if (open) {
      reset()
      await loadIndustries()
      await loadSchema()
    }
  },
)

watch(industry, loadSchema)
watch(() => entityForm.value.typeKey, loadEntityFields)
</script>

<style scoped>
.wizard {
  padding-block: 1.5rem;
  background-color: rgb(var(--v-theme-surface));
}

.wizard__steps {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0;
  padding-inline: 3rem;
}

.wizard__step {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
  flex: 1 1 0;
  max-inline-size: 15rem;
  min-inline-size: 0;
}


.wizard__dot {
  inline-size: 1.25rem;
  block-size: 1.25rem;
  border-radius: 50%;
  background-color: rgba(var(--v-theme-on-surface), 0.75);
  z-index: 1;
}

.wizard__dot--active {
  background-color: rgb(var(--v-theme-primary));
}

.wizard__step-label {
  font-size: 0.8125rem;
  white-space: nowrap;
}

.wizard__line {
  position: absolute;
  inset-block-start: 0.5625rem;
  inset-inline-start: 50%;
  inline-size: 100%;
  block-size: 0.09375rem;
  background-color: rgba(var(--v-theme-on-surface), 0.6);
}

.wizard__title {
  text-align: center;
  font-size: 1.75rem;
  font-weight: 600;
  padding-block: 1.5rem 0.5rem;
}

.wizard__body {
  max-block-size: 60vh;
}

.wizard__grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(15rem, 1fr));
  gap: 1.25rem;
}

.wizard__field {
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
  min-inline-size: 0;
}

.wizard__field--wide {
  grid-column: 1 / -1;
}

/*
 * A label that carries an information icon is taller than a plain one, which would start the control under it
 * lower than the control beside it. Reserving the icon's height for every label keeps the row aligned.
 */
.wizard__label {
  font-size: 0.875rem;
  line-height: 1.5;
  min-block-size: 1.5rem;
}

.wizard__required {
  color: rgb(var(--v-theme-error));
  margin-inline-end: 0.125rem;
}

.wizard__additional {
  display: grid;
  grid-template-columns: minmax(0, 2fr) minmax(0, 1fr);
  gap: 1.5rem;
}

.wizard__entity-form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  background-color: rgba(var(--v-theme-on-surface), 0.04);
  border-radius: 0.75rem;
  padding: 1.25rem;
}

.wizard__entity-actions {
  display: flex;
  justify-content: flex-end;
  gap: 0.5rem;
}

.wizard__added {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  border-inline-start: 0.0625rem solid rgba(var(--v-theme-on-surface), 0.15);
  padding-inline-start: 1.5rem;
}

.wizard__added-title {
  font-size: 1.125rem;
  font-weight: 600;
  border-block-end: 0.0625rem solid rgba(var(--v-theme-on-surface), 0.25);
  padding-block-end: 0.5rem;
}

.wizard__added-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.5rem;
  border-block-end: 0.0625rem solid rgba(var(--v-theme-on-surface), 0.15);
  padding-block-end: 0.5rem;
}

/* The entity being edited is marked, because the form and the list are otherwise two unrelated things. */
.wizard__added-item--edited {
  border-inline-start: 0.1875rem solid rgb(var(--v-theme-primary));
  padding-inline-start: 0.5rem;
}

.wizard__added-open {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  flex: 1 1 auto;
  min-inline-size: 0;
  text-align: start;
  background: none;
  border: none;
  padding: 0;
  cursor: pointer;
  color: inherit;
  font: inherit;
}

.wizard__added-open:hover,
.wizard__added-open:focus-visible {
  color: rgb(var(--v-theme-primary));
}

.wizard__added-hint {
  font-size: 0.8125rem;
  opacity: 0.7;
}

.wizard__empty {
  opacity: 0.7;
  font-size: 0.875rem;
}

.wizard__actions {
  padding-inline: 1.5rem;
}

@media (max-width: 60rem) {
  .wizard__additional {
    grid-template-columns: 1fr;
  }

  .wizard__added {
    border-inline-start: none;
    padding-inline-start: 0;
  }

  .wizard__line {
    inline-size: 6rem;
  }
}
</style>
