<template>
  <v-dialog
    :model-value="modelValue"
    max-width="56rem"
    scrollable
    @update:model-value="attemptClose"
  >
    <v-card class="edit-event">
      <v-card-title class="edit-event__title">
        Edit the event
      </v-card-title>

      <v-card-text class="edit-event__body">
        <div class="edit-event__grid">
          <div class="edit-event__field">
            <label
              class="edit-event__label"
              for="edit-name"
            >
              <span class="edit-event__required">*</span>Name
              <SkyInfoIcon label="What Name means">
                The name this event is listed and searched by. It cannot be left empty: an event without a
                name is one nobody can tell apart from the next one.
              </SkyInfoIcon>
            </label>
            <v-text-field
              id="edit-name"
              v-model="name"
              placeholder="Enter event name"
            />
          </div>

          <div class="edit-event__field">
            <label
              class="edit-event__label"
              for="edit-platform"
            >
              Platform
              <SkyInfoIcon label="What Platform means">
                The platform the event was produced on. Typing a name no event carries yet creates it.
              </SkyInfoIcon>
            </label>
            <v-text-field
              id="edit-platform"
              v-model="platform"
              placeholder="Enter platform"
            />
          </div>

          <div class="edit-event__field">
            <label
              class="edit-event__label"
              for="edit-status"
            >Status</label>
            <v-select
              id="edit-status"
              v-model="status"
              :items="STATUS_OPTIONS"
            />
          </div>

          <div class="edit-event__field">
            <label
              class="edit-event__label"
              for="edit-date"
            >Event date</label>
            <v-text-field
              id="edit-date"
              v-model="eventDate"
              type="date"
            />
          </div>

          <div class="edit-event__field">
            <label
              class="edit-event__label"
              for="edit-reference"
            >
              Reference ID
              <SkyInfoIcon label="What Reference ID means">
                The identifier you already know this event by, carried over from wherever it was reported.
                It is yours to choose, it has to be unique, and it is the one you can search by. The EVENT ID
                beside it is generated by the system and can never be set or changed.
              </SkyInfoIcon>
            </label>
            <v-text-field
              id="edit-reference"
              v-model="referenceId"
              placeholder="Enter reference id"
            />
          </div>

          <div class="edit-event__field">
            <label
              class="edit-event__label"
              for="edit-result"
            >Experiment result</label>
            <v-select
              id="edit-result"
              v-model="experimentResult"
              :items="RESULT_OPTIONS"
              placeholder="Not known yet"
              clearable
            />
          </div>

          <div class="edit-event__field edit-event__field--wide">
            <label
              class="edit-event__label"
              for="edit-notes"
            >
              Information
              <SkyInfoIcon label="What Information means">
                Anything worth knowing about this event, written as freely as you like. The line breaks you
                type are kept, so the text is read back laid out the way you wrote it.
              </SkyInfoIcon>
            </label>
            <v-textarea
              id="edit-notes"
              v-model="notes"
              rows="3"
            />
          </div>
        </div>

        <MetadataFieldsPanel
          v-model="values"
          :fields="fields"
          title="Metadata fields"
        />

        <!--
          Every edit joins the history of the event, and a history without reasons only says that somebody
          changed something. The reason is therefore asked for before the change can be saved.
        -->
        <div class="edit-event__field edit-event__field--wide">
          <label
            class="edit-event__label"
            for="edit-reason"
          ><span class="edit-event__required">*</span>Reason for this edit</label>
          <v-text-field
            id="edit-reason"
            v-model="reason"
            placeholder="For example: the platform was recorded wrong on upload"
          />
        </div>

        <div class="edit-event__files">
          <h3 class="edit-event__section">
            Add more files
          </h3>
          <FileDropzone
            :files="newFiles"
            @update:files="newFiles = $event"
          />
        </div>
      </v-card-text>

      <v-card-actions class="edit-event__actions">
        <!--
          A button that is disabled without saying why reads as a broken button, so the reason it is waiting
          for is spelled out beside it.
        -->
        <span
          v-if="blockedReason.length > 0"
          class="edit-event__blocked"
        >
          {{ blockedReason }}
        </span>
        <v-spacer />
        <v-btn
          variant="text"
          @click="attemptClose"
        >
          Cancel
        </v-btn>
        <v-btn
          color="primary"
          :loading="saving"
          :disabled="!canSave"
          @click="submit"
        >
          Save
        </v-btn>
      </v-card-actions>
    </v-card>

    <UnsavedChangesDialog
      v-model="confirmOpen"
      @discard="discard"
    />
  </v-dialog>
</template>

<script lang="ts">
import type { EventStatus, ExperimentResult, JsonValue } from '@/models/common'
import { SkyDropzone as FileDropzone, SkyInfoIcon, toDateInput, toIsoDate } from '@skyscanner/sky-ui'
import type { EventDetail } from '@/models/event'
import type { FieldDefinition } from '@/models/field'

interface Props {
  modelValue: boolean
  event: EventDetail
}

interface Emits {
  (event: 'update:modelValue', value: boolean): void
  (event: 'saved', updated: EventDetail): void
}

/** What the user is told while Save is refusing to be pressed. */
const NOTHING_CHANGED = 'Nothing has changed yet'
const NAME_MISSING = 'An event has to keep a name'
const REASON_MISSING = 'A reason is needed before this can be saved'
</script>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'

import MetadataFieldsPanel from '@/components/MetadataFieldsPanel.vue'
import UnsavedChangesDialog from '@/components/UnsavedChangesDialog.vue'
import { useDirtyGuard } from '@/composables/useDirtyGuard'
import { useSnackbar } from '@/composables/useSnackbar'
import { updateEvent } from '@/requests/events'
import { listFields } from '@/requests/schema'
import { uploadArtifacts } from '@/requests/storage'
import { toMetadataAttributes, toValueMap } from '@/utils/rows'

const STATUS_OPTIONS: EventStatus[] = ['draft', 'raw', 'parsed', 'partial', 'failed', 'archived']
const RESULT_OPTIONS: ExperimentResult[] = ['successful', 'partial', 'failed']

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const { notify, reportError } = useSnackbar()

const name = ref<string>('')
const referenceId = ref<string>('')
const platform = ref<string>('')
const status = ref<EventStatus>('raw')
const experimentResult = ref<ExperimentResult | null>(null)
const eventDate = ref<string>('')
const notes = ref<string>('')
const values = ref<Record<string, JsonValue>>({})
const fields = ref<FieldDefinition[]>([])
const newFiles = ref<File[]>([])
const reason = ref<string>('')
const saving = ref<boolean>(false)

/* What the dialog was filled with when it opened, which is what an edit is measured against. */
const openedWith = ref<string>('')

/**
 * Describe everything an edit can change as one comparable string.
 *
 * The reason is deliberately left out: it explains a change rather than being one, so typing a reason on its
 * own is not an edit. Files carry no value equality, so a picked file is described by what identifies it.
 */
const snapshot = (): string =>
  JSON.stringify({
    name: name.value,
    referenceId: referenceId.value,
    platform: platform.value,
    status: status.value,
    experimentResult: experimentResult.value,
    eventDate: eventDate.value,
    notes: notes.value,
    values: values.value,
    files: newFiles.value.map((file) => `${file.name}:${file.size}`),
  })

/*
 * Saving an event nobody changed used to be possible: it bumped the timestamp, mailed every subscriber and
 * left a line in the history for a change that never happened. The dialog now compares what it holds against
 * what it opened with, and the reason is asked for on top of a real change rather than instead of one.
 */
const isDirty = computed<boolean>(() => snapshot() !== openedWith.value)

const blockedReason = computed<string>(() => {
  if (name.value.trim().length === 0) {
    return NAME_MISSING
  }

  if (!isDirty.value) {
    return NOTHING_CHANGED
  }

  if (reason.value.trim().length === 0) {
    return REASON_MISSING
  }

  return ''
})

const canSave = computed<boolean>(() => blockedReason.value.length === 0)

const fill = async (): Promise<void> => {
  name.value = props.event.name
  referenceId.value = props.event.reference_id
  platform.value = props.event.platform
  status.value = props.event.status
  experimentResult.value = props.event.experiment_result
  eventDate.value = toDateInput(props.event.event_date)
  notes.value = props.event.notes
  values.value = toValueMap(props.event.metadata)
  newFiles.value = []
  reason.value = ''
  openedWith.value = snapshot()

  try {
    fields.value = await listFields({ scope: 'event', industry: props.event.industry })
  } catch (error) {
    reportError(error)
  }
}

const close = () => {
  emit('update:modelValue', false)
}

/* Whatever was typed into the reason is worth keeping as well, so it counts towards leaving with changes. */
const { confirmOpen, attemptClose, discard } = useDirtyGuard({
  isDirty: () => isDirty.value || reason.value.trim().length > 0,
  close,
})

const submit = async (): Promise<void> => {
  if (!canSave.value || saving.value) {
    return
  }

  saving.value = true
  try {
    const uploaded = await uploadArtifacts(newFiles.value, {
      ownerKind: 'events',
      ownerId: props.event.id,
      kind: 'additional',
      folder: null,
      descriptor: 'Files added after the event was created',
    })
    const updated = await updateEvent(props.event.id, {
      reason: reason.value.trim(),
      name: name.value.trim(),
      reference_id: referenceId.value.trim(),
      platform: platform.value,
      status: status.value,
      experiment_result: experimentResult.value,
      event_date: toIsoDate(eventDate.value),
      notes: notes.value,
      additional_files: [...props.event.additional_files, ...uploaded],
      metadata: toMetadataAttributes(values.value),
    })
    notify('The event was updated', 'success')
    emit('saved', updated)
    close()
  } catch (error) {
    reportError(error)
  } finally {
    saving.value = false
  }
}

watch(
  () => props.modelValue,
  (open) => {
    if (open) {
      void fill()
    }
  },
)
</script>

<style scoped>
.edit-event {
  background-color: rgb(var(--v-theme-surface));
}

.edit-event__title {
  font-size: 1.25rem;
  font-weight: 600;
}

.edit-event__body {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
  max-block-size: 65vh;
}

.edit-event__grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr));
  gap: 1rem;
}

.edit-event__field {
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
  min-inline-size: 0;
}

.edit-event__field--wide {
  grid-column: 1 / -1;
}

/*
 * A label that carries an information icon is taller than a plain one, which would start the control under it
 * lower than the control beside it. Reserving the icon's height for every label keeps the row aligned.
 */
.edit-event__label {
  font-size: 0.875rem;
  line-height: 1.5;
  min-block-size: 1.5rem;
}

.edit-event__required {
  color: rgb(var(--v-theme-error));
  margin-inline-end: 0.125rem;
}

.edit-event__section {
  font-size: 1rem;
  font-weight: 600;
  padding-block-end: 0.5rem;
}

.edit-event__actions {
  padding-inline: 1rem;
}

.edit-event__blocked {
  font-size: 0.8125rem;
  opacity: 0.7;
}
</style>
