/**
 * Everything this client says, in both languages.
 *
 * The shared library ships the vocabulary of the table itself - the filter chips, the pager, the viewers a
 * cell opens - and this adds the vocabulary of the inventory: what a row is, what its toolbar offers, what
 * its dialogs ask for. The two are looked up through the same `t`, and this is registered second, which is
 * what lets a phrase here reword one of the library's: an inventory counts events rather than rows, and
 * both are the same pagination bar.
 *
 * What is deliberately not here is the column headers. Those are generated by the service out of the
 * declarations, so the service is where they are named - in both languages, on the column itself - and the
 * client swaps one for the other where the configuration lands. Nor are the names of the industries, the
 * types and the platforms: those are written by the people using the inventory, and translating them would
 * mean inventing words for somebody else's vocabulary. A declared field can carry a Hebrew name of its own,
 * and that is the only place the inventory's own words are ever shown in two languages.
 */

import type { Translations } from '@truth-platform/core-ui'

const SKYSCANNER_TRANSLATIONS: Translations = {
  en: {
    /* The application itself. */
    'app.settings': 'Settings',
    'app.account': 'Account',
    'app.subscriptions': 'Subscriptions',
    'app.industries': 'Industries',
    'app.platforms': 'Platforms',
    'app.schema': 'Schema',
    'app.types': 'Types',
    'app.noAccount': 'No account settings yet',
    'app.identityNote': 'The system reads your identity from the proxy that signed you in.',
    'app.toLight': 'Switch to the light theme',
    'app.toDark': 'Switch to the dark theme',

    /* Declaring a field, which is the one place the inventory's own vocabulary is written in two languages. */
    'schema.name': 'Name',
    'schema.nameHebrew': 'Hebrew name',
    'schema.nameHebrewHint':
      'Optional. What this field is called - as a column and as an input - when the interface is read in ' +
      'Hebrew. Left empty, it keeps its name above in both languages.',

    /* The bar under the table counts events rather than the rows the library counts by default. */
    'pagination.empty': 'No events',
    'pagination.range': '{first} – {last} of {total} events',

    /* The row of industries above the table. */
    'tabs.all': 'All',
    'tabs.label': 'Industries',

    /* The toolbar above the table. */
    'toolbar.search': 'Search',
    'toolbar.parsed': 'PARSED',
    'toolbar.notParsed': 'NOT PARSED',
    'toolbar.all': 'ALL',
    'toolbar.sortBy': 'Sort by',
    'toolbar.columns': 'Columns',
    'toolbar.views': 'Views',
    'toolbar.defaultView': 'Default view',
    'toolbar.saveView': 'Save current view',
    'toolbar.shared': 'Shared',
    'toolbar.private': 'Private',
    'toolbar.export': 'Export',
    'toolbar.wholeView': 'Whole current view',
    'toolbar.selectedOnly': 'Selected only - {count}',
    'toolbar.intoInventory': 'Into this inventory',
    'toolbar.exportCsv': 'Export as CSV',
    'toolbar.exportJson': 'Export as JSON',
    'toolbar.exportFiles': 'Download all files as ZIP',
    'toolbar.exportSelectedFiles': 'Download their files as ZIP',
    'toolbar.exportBundle': 'Export as a bundle, to import elsewhere',
    'toolbar.import': 'Import a bundle',
    'toolbar.selectAll': 'SELECT ALL',
    'toolbar.selected': 'SELECTED {count}',
    'toolbar.newEvent': 'EVENT',
    'toolbar.fullscreen': 'Show the table full screen',
    'toolbar.leaveFullscreen': 'Leave the full screen table',

    /* The panels opened underneath the rows. */
    'inventory.collapseAll': 'COLLAPSE ALL',
    'inventory.exported': 'The current view was exported',
    'inventory.exportedSelected': '{count} selected event(s) were exported',
    'inventory.packing': 'The archive is being packed, this can take a while',
    'inventory.packed': 'The archive was downloaded',

    /* Writing the inventory out whole, and reading one back in. */
    'import.title': 'Import a bundle',
    'import.note':
      'A bundle written by the bundle export of this inventory, or of another one. Everything in it that ' +
      'is not already here is written: the industries, the types, the platforms and the declared fields ' +
      'first, then the files, then the events that point at them. An event already here is left alone.',
    'import.pick': 'Bundle file',
    'import.size': 'The bundle is {size}.',
    'import.restore': 'Restore',
    'import.close': 'Close',
    'import.started': 'The bundle is being restored, this can take a while',
    'import.running': 'Restoring — the events, their declarations and their files.',
    'import.done': '{events} events and {files} files were restored.',
    'import.declarations':
      'Declared as well: {industries} industries, {types} types, {platforms} platforms, {fields} fields.',
    'import.skipped': '{count} events were already here and were left alone.',
    'import.failures': 'What could not be written',
    'bundle.packing': 'The bundle is being packed, this can take a while',
    'bundle.packed': 'The bundle was downloaded',

    /* Saving the arrangement of the table. */
    'view.saveTitle': 'Save the current view',
    'view.name': 'Name',
    'view.description': 'Description',
    'view.share': 'Share with other users',
    'view.sharedNote': 'Every user of the system will see this view.',
    'view.privateNote': 'This view stays private and is kept in this browser only.',
  },
  he: {
    'app.settings': 'הגדרות',
    'app.account': 'חשבון',
    'app.subscriptions': 'מינויים',
    'app.industries': 'תעשיות',
    'app.platforms': 'פלטפורמות',
    'app.schema': 'סכמה',
    'app.types': 'סוגים',
    'app.noAccount': 'אין עדיין הגדרות חשבון',
    'app.identityNote': 'המערכת קוראת את הזהות שלכם מהשרת שדרכו נכנסתם.',
    'app.toLight': 'מעבר לערכת הנושא הבהירה',
    'app.toDark': 'מעבר לערכת הנושא הכהה',

    'schema.name': 'שם',
    'schema.nameHebrew': 'שם בעברית',
    'schema.nameHebrewHint':
      'אופציונלי. איך השדה הזה נקרא — כעמודה וכשדה קלט — כשהממשק מוצג בעברית. אם נשאר ריק, הוא ישמור על ' +
      'השם שלמעלה בשתי השפות.',

    /* The count leads the sentence rather than sitting inside it, so the digits keep their own direction. */
    'pagination.empty': 'אין אירועים',
    'pagination.range': 'מתוך {total} אירועים מוצגים {first} עד {last}',

    'tabs.all': 'הכול',
    'tabs.label': 'תעשיות',

    'toolbar.search': 'חיפוש',
    'toolbar.parsed': 'מפוענח',
    'toolbar.notParsed': 'לא מפוענח',
    'toolbar.all': 'הכול',
    'toolbar.sortBy': 'מיון לפי',
    'toolbar.columns': 'עמודות',
    'toolbar.views': 'תצוגות',
    'toolbar.defaultView': 'תצוגת ברירת מחדל',
    'toolbar.saveView': 'שמירת התצוגה הנוכחית',
    'toolbar.shared': 'משותפת',
    'toolbar.private': 'פרטית',
    'toolbar.export': 'ייצוא',
    'toolbar.wholeView': 'כל התצוגה הנוכחית',
    'toolbar.selectedOnly': 'הנבחרים בלבד - {count}',
    'toolbar.intoInventory': 'אל תוך המלאי הזה',
    'toolbar.exportCsv': 'ייצוא כ־CSV',
    'toolbar.exportJson': 'ייצוא כ־JSON',
    'toolbar.exportFiles': 'הורדת כל הקבצים כ־ZIP',
    'toolbar.exportSelectedFiles': 'הורדת הקבצים שלהם כ־ZIP',
    'toolbar.exportBundle': 'ייצוא כחבילה, לייבוא במקום אחר',
    'toolbar.import': 'ייבוא חבילה',
    'toolbar.selectAll': 'בחירת הכול',
    'toolbar.selected': 'נבחרו {count}',
    'toolbar.newEvent': 'אירוע',
    'toolbar.fullscreen': 'הצגת הטבלה במסך מלא',
    'toolbar.leaveFullscreen': 'יציאה ממסך מלא',

    'inventory.collapseAll': 'סגירת הכול',
    'inventory.exported': 'התצוגה הנוכחית יוצאה',
    'inventory.exportedSelected': 'יוצאו {count} אירועים שנבחרו',
    'inventory.packing': 'הארכיון נארז, זה עשוי לקחת זמן',
    'inventory.packed': 'הארכיון הורד',

    'import.title': 'ייבוא חבילה',
    'import.note':
      'חבילה שנכתבה על ידי ייצוא החבילה של המלאי הזה, או של מלאי אחר. כל מה שבתוכה ולא נמצא כאן כבר ' +
      'ייכתב: קודם התעשיות, הסוגים, הפלטפורמות והשדות המוגדרים, אחר כך הקבצים, ואחריהם האירועים ' +
      'שמצביעים עליהם. אירוע שכבר נמצא כאן נשאר כפי שהוא.',
    'import.pick': 'קובץ החבילה',
    'import.size': 'גודל החבילה {size}.',
    'import.restore': 'שחזור',
    'import.close': 'סגירה',
    'import.started': 'החבילה משוחזרת, זה עשוי לקחת זמן',
    'import.running': 'משחזר — את האירועים, את ההגדרות שלהם ואת הקבצים שלהם.',
    'import.done': 'שוחזרו {events} אירועים ו־{files} קבצים.',
    'import.declarations':
      'הוגדרו גם: {industries} תעשיות, {types} סוגים, {platforms} פלטפורמות, {fields} שדות.',
    'import.skipped': '{count} אירועים כבר היו כאן ונשארו כפי שהם.',
    'import.failures': 'מה שלא נכתב',
    'bundle.packing': 'החבילה נארזת, זה עשוי לקחת זמן',
    'bundle.packed': 'החבילה הורדה',

    'view.saveTitle': 'שמירת התצוגה הנוכחית',
    'view.name': 'שם',
    'view.description': 'תיאור',
    'view.share': 'שיתוף עם משתמשים אחרים',
    'view.sharedNote': 'כל משתמשי המערכת יראו את התצוגה הזו.',
    'view.privateNote': 'התצוגה הזו נשארת פרטית ונשמרת בדפדפן הזה בלבד.',
  },
}

export { SKYSCANNER_TRANSLATIONS }
