/**
 * The composable that binds the generated inventory table to the API and to the actions of the toolbar.
 */

import { createGridController, type GridController, type RowsQuery } from '@truth-platform/ag-grid-ts'
import { language, localiseColumns } from '@truth-platform/core-ui'
import { watch } from 'vue'

import type { ParseState } from '@/models/common'
import type { GeneratedGridConfiguration, GridRow, GridRowsPage } from '@/models/grid'
import type { EventExportRequest, GridRowsRequest } from '@/models/query'
import { readEventColumns, readEventRows } from '@/requests/grid'

const DEFAULT_PAGE_SIZE = 25
const EXPORT_PAGE_SIZE = 500

/**
 * Turn the query of the grid controller into the request payload the backend expects.
 */
const toRowsRequest = (query: RowsQuery): GridRowsRequest => ({
  search: query.search,
  industry: query.industry,
  parse_state: query.parseState as ParseState,
  filters: query.filters,
  sort: query.sort,
  page: query.page,
  page_size: query.pageSize,
  columns: [],
})

/**
 * Build the controller of the inventory table, already wired to the endpoints of the events service.
 */
const useEventsGrid = (industry: string | null): GridController => {
  const controller = createGridController({
    /*
     * The columns are generated by the service, headers and all, and each of them arrives carrying both the
     * name it is known by and the Hebrew name somebody wrote down for it. Which of the two ends up on screen
     * is decided once, here, because everything downstream - the grid, the chips, the pills, the column
     * picker, the viewer a long value opens - reads the one header this leaves behind.
     */
    loadConfiguration: async (currentIndustry): Promise<GeneratedGridConfiguration> =>
      localiseColumns(await readEventColumns(currentIndustry)),
    loadRows: (query): Promise<GridRowsPage> => readEventRows(toRowsRequest(query)),
    pageSize: DEFAULT_PAGE_SIZE,
  })
  controller.industry.value = industry

  /*
   * A change of language changes every header at once, which is the same rebuild a change of declarations
   * is - the columns are not what they were. It costs one reading of the configuration and leaves the rows
   * exactly where they are, because nothing about which rows are on screen has changed.
   */
  watch(language, () => {
    void controller.refreshConfiguration()
  })

  return controller
}

/**
 * Build the request payload of the current view, used by the export action of the toolbar.
 *
 * The export follows the table as it stands on screen, so it carries the very filters and ordering the grid
 * is showing. Handing it a list of identifiers narrows it further, down to the rows the user ticked.
 */
const buildExportRequest = (
  controller: GridController,
  columns: string[],
  eventIds: string[] = [],
): EventExportRequest => ({
  search: controller.search.value.length > 0 ? controller.search.value : null,
  industry: controller.industry.value,
  parse_state: controller.parseState.value as ParseState,
  filters: controller.filterConditions.value,
  sort: controller.sortSpecifications.value,
  page: 1,
  page_size: EXPORT_PAGE_SIZE,
  columns,
  event_ids: eventIds,
})

/**
 * Find one row of the current block by its identifier.
 */
const findRowById = (rows: GridRow[], rowId: string): GridRow | undefined =>
  rows.find((row) => String(row.id) === rowId)

export { DEFAULT_PAGE_SIZE, buildExportRequest, findRowById, toRowsRequest, useEventsGrid }
