/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/assumptions/': RouteRecordInfo<'/assumptions/', '/assumptions', Record<never, never>, Record<never, never>>,
    '/assumptions/[id]': RouteRecordInfo<'/assumptions/[id]', '/assumptions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/industries/': RouteRecordInfo<'/industries/', '/industries', Record<never, never>, Record<never, never>>,
    '/industries/[id]': RouteRecordInfo<'/industries/[id]', '/industries/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/schemas/': RouteRecordInfo<'/schemas/', '/schemas', Record<never, never>, Record<never, never>>,
    '/schemas/[id]': RouteRecordInfo<'/schemas/[id]', '/schemas/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/snapshots/': RouteRecordInfo<'/snapshots/', '/snapshots', Record<never, never>, Record<never, never>>,
  }
}
