<template>
  <v-app>
    <v-main class="app-shell">
      <RouterView />
      <AppSnackbar />
    </v-main>
  </v-app>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { RouterView } from 'vue-router'

import AppSnackbar from '@/components/AppSnackbar.vue'
import { useSnackbar } from '@/composables/useSnackbar'
import { useIndustries } from '@/composables/useIndustries'

const { load } = useIndustries()
const { reportError } = useSnackbar()

onMounted(async () => {
  try {
    await load()
  } catch (error) {
    reportError(error)
  }
})
</script>

<style>
/*
 * The two families of the design. Inter is the interface type and carries everything the user reads inside
 * the application: controls, labels, headings and table cells alike. Kufam is the display type, and in the
 * mockups it appears in one single place - the wordmark - so it is scoped to exactly that.
 */
:root {
  --sky-font-body: 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif;
  --sky-font-display: 'Kufam', 'Inter', 'Segoe UI', system-ui, sans-serif;
}

html,
body,
#app {
  block-size: 100%;
}

/*
 * Vuetify names its own family on the application root and on several of its components, so the interface
 * type has to be restated at least as specifically to win. Menus and dialogs are teleported out of the
 * application root into the overlay container, which is why that is listed as well.
 */
.v-application,
.v-application .v-btn,
.v-application .v-field__input,
.v-application .v-list-item-title,
.v-overlay-container,
.v-overlay-container .v-btn,
.v-overlay-container .v-list-item-title {
  font-family: var(--sky-font-body);
}

.sky-display {
  font-family: var(--sky-font-display);
}

.app-shell {
  min-block-size: 100vh;
  background-color: rgb(var(--v-theme-background));
}

/*
 * Every page grows with its content and lets the browser scroll it. A page that renders a table used to pin
 * itself to the viewport instead, which left the table a letterbox between its toolbar and its pager; the
 * table now renders its whole block of rows and the page carries the scrollbar for it.
 */
.sky-page {
  display: flex;
  flex-direction: column;
  min-block-size: 100vh;
}

.sky-page__content {
  display: flex;
  flex-direction: column;
  flex: 1 1 auto;
  padding-inline: 2rem;
  padding-block-end: 1rem;
  min-inline-size: 0;
}

/*
 * A cell of the table has to keep what it holds inside its own column. The grid only clips the cells whose
 * height is fixed, so a cell that grows to fit its content - a list of files, above all - used to let a long
 * file name run straight across the columns beside it. Clipping is stated here for every cell, and the
 * children are allowed to shrink below their content so that the value ellipsises instead of being cut.
 */
.sky-cell {
  display: flex;
  align-items: center;
  min-inline-size: 0;
  overflow: hidden;
}

.sky-cell > * {
  min-inline-size: 0;
  max-inline-size: 100%;
}

/*
 * The selection column is generated by the grid itself and therefore never receives the class every declared
 * column carries. Left alone its checkbox sits at the top of the cell, which shows as soon as a row grows to
 * fit a list of files, so it is centred here to sit on the same line as the values next to it.
 */
.ag-cell[col-id='ag-Grid-SelectionColumn'],
.ag-header-cell[col-id='ag-Grid-SelectionColumn'] .ag-header-select-all {
  display: flex;
  align-items: center;
  justify-content: flex-start;
}

.ag-cell[col-id='ag-Grid-SelectionColumn'] .ag-cell-wrapper {
  display: flex;
  align-items: center;
  block-size: 100%;
}

@media (max-width: 48rem) {
  .sky-page__content {
    padding-inline: 1rem;
  }
}
</style>
