/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/events/': RouteRecordInfo<'/events/', '/events', Record<never, never>, Record<never, never>>,
    '/events/[id]': RouteRecordInfo<'/events/[id]', '/events/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/industries/': RouteRecordInfo<'/industries/', '/industries', Record<never, never>, Record<never, never>>,
    '/industries/[key]': RouteRecordInfo<'/industries/[key]', '/industries/:key', { key: ParamValue<true> }, { key: ParamValue<false> }>,
    '/schema/': RouteRecordInfo<'/schema/', '/schema', Record<never, never>, Record<never, never>>,
    '/subscriptions/': RouteRecordInfo<'/subscriptions/', '/subscriptions', Record<never, never>, Record<never, never>>,
    '/types/': RouteRecordInfo<'/types/', '/types', Record<never, never>, Record<never, never>>,
  }
}
